services:
  - type: web
    name: edutrack-be
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_REFRESH_EXPIRATION
        value: 7d
      - key: JWT_REFRESH_COOKIE_NAME
        value: edutrack_refresh_token
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: OTP_EXPIRES_MINUTES
        value: "5"
      - key: OTP_RESEND_COOLDOWN_SECONDS
        value: "60"
      - key: FRONTEND_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_STUDENT_AVATAR_FOLDER
        value: edutrack/student-avatars
