export const PREVIEW_RECEIPT = {
  receiptNumber: 'Bản xem trước',
  issuedAt: '2026-09-13',
  periodStart: '2026-08-21',
  periodEnd: '2026-09-04',
  studentSnapshot: { fullName: 'Nguyễn Minh Anh' },
  classSnapshot: { className: 'Tiếng Anh lớp 8' },
  teacherSnapshot: {
    fullName: 'Ms. Cheese',
    bankAccountName: 'Giáo viên',
    bankAccountNumber: '0000000000',
    bankName: 'Vietcombank',
    bankCode: 'VCB',
    bankBin: '970436',
    bankLogoUrl: 'https://cdn.vietqr.io/img/VCB.png',
    phone: '0900000000',
  },
  totalAmount: 600000,
  paymentNote: 'Nội dung chuyển khoản: Họ tên học sinh - Mã hóa đơn.',
  strengthsComment: 'Chủ động tham gia bài học và hoàn thành bài tập.',
  improvementsComment: 'Tiếp tục luyện phát âm và ôn từ vựng.',
  generalComment: 'Có tiến bộ trong kỳ học.',
  sessions: [
    {
      sequence: 1,
      date: '2026-08-21',
      topic: 'Unit 1: Leisure time',
      content: 'Getting started - Vocabulary',
      amount: 150000,
      unitPrice: 150000,
    },
    {
      sequence: 2,
      date: '2026-08-26',
      topic: 'Ôn bài',
      amount: 150000,
      unitPrice: 150000,
    },
    {
      sequence: 3,
      date: '2026-08-28',
      topic: 'Leisure time - like/dislike',
      amount: 150000,
      unitPrice: 150000,
    },
    {
      sequence: 4,
      date: '2026-09-04',
      topic: 'Speaking practice',
      amount: 150000,
      unitPrice: 150000,
    },
  ],
  exams: [],
};
